---
 - name: Install Dependent Packages
   yum:
     name: "{{ packages }}"
     state: present
   vars:
     packages:
       - "java-1.8.0-openjdk"
       - "java-1.8.0-openjdk-devel"

 - name: Install Jenkins Yum Repo
   uri:
     url: "{{ jenkins_repo_url }}"
     dest: "/etc/yum.repos.d/jenkins.repo"
     creates: "/etc/yum.repos.d/jenkins.repo"

 - name: Import Jenkins Repo Key
   rpm_key:
     key: "{{ jenkins_repo_key_url }}"
     state: present

 - name: Yum Install Tools
   yum:
     name: "{{ packages }}"
     state: latest
   vars:
     packages:
       - "jenkins"
