---
- name: Disable services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    daemon_reload: true
    masked: true
  ignore_errors: true
  loop:
    - ntpd
    - postfix
  when: ansible_distribution_major_version <= "7"


# 禁用dnf makecache,防止低内存配置的服务器内存溢出
- name: Disable dnf-makecache.timer
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    daemon_reload: true
  loop:
    - dnf-makecache.timer
  when: ansible_distribution_major_version >= "8" and ansible_memtotal_mb <= 2048
