---
#- name: Add redis os group
#  group:
#    name: "{{ group }}"
#    state: present
#    system: yes
#
#- name: Add redis os user
#  user:
#    name: "{{ user }}"
#    group: "{{ group }}"
#    createhome: no
#    shell: /sbin/nologin
#    state: present
#    system: yes

- name: Install redis
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - redis

- name: Modify sys args
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  with_items:
    - { name: vm.overcommit_memory, value: 1 }

- name: Setup redis configuration
  blockinfile:
    path: "/etc/redis/redis.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK Redis.conf"
    block: "{{ lookup('template', 'redis.conf.j2') }}"

- name: Enable redis service
  systemd:
    name: redis
    state: restarted
    enabled: true
    daemon_reload: true

- name: Make sure redis service is running
  ansible.builtin.service_facts: {}
  register: __service_status
  until: "__service_status.ansible_facts.services['redis-server'].state == 'running'"
  retries: 10
  delay: 5
