---
- name: Include os tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Add nginx group
  group:
    name: "{{ nginx_os_group }}"
    state: present
    system: yes

- name: Add nginx user
  user:
    name: "{{ nginx_os_user }}"
    group: "{{ nginx_os_group }}"
    createhome: no
    shell: /sbin/nologin
    state: present
    system: yes

- name: Set regular clean nginx log
  template: 
    src: nginx.logrotate.j2
    dest: /etc/logrotate.d/nginx

- name: Sync nginx conf.d and ssl.d
  synchronize:
    src: "{{ item }}"
    dest: "{{ nginx_config_dir }}"
  loop:
    - "conf.d"
    - "ssl.d"

- name: Create nginx sites configuration directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ nginx_sites_enabled_dir }}"
    - "{{ nginx_sites_available_dir }}"

- name: Create log directory
  file:
    path: "{{ nginx_log_dir }}" 
    owner: "{{ nginx_os_user }}"
    group: "{{ nginx_os_group }}"
    state: directory

- name: Setup nginx.conf
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_config_dir }}/nginx.conf"

- name: Ensure nginx service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: nginx
    state: restarted
    enabled: true
  notify: nginx service is running

