---
- name: Include OS Tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Add nginx group
  group:
    name: "{{ nginx_group }}"
    state: present
    system: yes

- name: Add nginx user
  user:
    name: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    createhome: no
    shell: /sbin/nologin
    state: present
    system: yes

- name: Setup nginx.conf
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_confdir }}/nginx.conf"

- name: Sync nginx conf.d and ssl.d
  synchronize:
    src: "{{ item }}"
    dest: "{{ nginx_confdir }}"
  loop:
    - "conf.d"
    - "ssl.d"

- name: Create nginx sites directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ nginx_sites_enabled_confdir }}"
    - "{{ nginx_sites_available_confdir }}"

- name: Create Logs Dir
  file:
    path: "{{ nginx_logdir }}" 
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    state: directory

- name: Set Regular Clean Nginx Logs
  template: 
    src: nginx.logrotate.j2
    dest: /etc/logrotate.d/nginx

- name: Enable Nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes
...
