---
- name: Setup nginx repo
  copy:
    src: "nginx.repo"
    dest: "/etc/yum.repos.d/nginx.repo"

- name: Allow http and https connections
  firewalld:
    zone: public
    service: "{{ item }}"
    immediate: yes
    permanent: true
    state: enabled
  with_items:
    - "http"
    - "https"
