---
galaxy_info:
  author: "tony chen"
  company: Zeroio
  license: license (BSD)
  min_ansible_version: 2.6
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
        - noble
    - name: EL
      versions:
        - 7
        - 8
        - 9
  categories:
    - software
dependencies: 
  - role: nginx
  - role: php-fpm
  - role: mysql
  - role: zabbix-release
  - role: zabbix-agent
    set_config: false
