---
- name: Ensure prerequisites are installed
  apt:
    name: software-properties-common
    state: latest

- name: Add Ondřej Surý's PHP PPA repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

- name: Install PHP and its extensions
  apt:
    name: "{{ packages }}"
    state: latest
  notify: restart php-fpm
  vars:
    packages:
      - "php{{ php_version }}"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-bcmath"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-mcrypt"  # 注意：在 PHP 7.2 及以上版本中已被废弃
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-redis"  
      - "php{{ php_version }}-igbinary" 
