---
 - name: Add PHP group
   group:
     name: "{{ php_group }}"
     state: present
     system: true

 - name: Add PHP user
   user:
     name: "{{ php_user }}"
     group: "{{ php_group }}"
     createhome: false
     shell: /sbin/nologin
     state: present
     system: true

 - name: Include OS Tasks
   include_tasks: "{{ ansible_os_family }}.yml"

 - name: Copy default process pool configure
   template:
     src: "demo.php.com.conf.j2"
     dest: "{{ php_fpm_confdir }}/demo.php.com"

 - name: Setup php.ini
   blockinfile:
     path: "{{ php_config_file }}"
     marker: "# {mark} ANSIBLE MANAGED BLOCK PHP.INI"
     block: "{{ lookup('file', 'php.ini') }}"

 - name: Change owner of the log's directory
   file:
     path: "{{ php_fpm_logdir }}"
     owner: "{{ php_user }}" 
     group: "{{ php_group }}"   
     recurse: true            
     state: directory 

 - name: Enable php-fpm service
   systemd:
     name: "{{ php_fpm_systemd_service }}"
     state: restarted
     enabled: true
     daemon_reload: true

...
