---
- name: Set REMI Repo
  yum:
    name: "https://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    disable_gpg_check: yes
    state: present

- name: Set PHP Module
  block:
  - name: Reset PHP Module
    command: dnf module reset php -y
 
  - name: Enable PHP Module
    command: dnf module enable php:remi-{{ php_version }} -y
  when: ansible_distribution_major_version > '7'

- name: Install PHP
  yum:
    name: "{{ packages }}"
    allow_downgrade: yes
    enablerepo: "remi-php{{ php_version| replace('.', '')}}"
    state: latest
  vars:
    packages:
      - "php"
      - "php-fpm"
      - "php-gd"
      - "php-bcmath"
      - "php-process"
      - "php-pecl-zip"
      - "php-pecl-mcrypt"
      - "php-pecl-mbstring"
      - "php-pecl-redis"
      - "php-pecl-igbinary-devel"
      - "php-pecl-mysql"

