---
# tasks file for consul
- name: Include os tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install Consul
  ansible.builtin.package:
    name: consul
    state: latest

- name: Ensure consul service is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: consul
    state: restarted
    enabled: true

- name: Make sure consul service is running
  ansible.builtin.service_facts: {}
  register: __service_status
  until: "__service_status.ansible_facts.services['consul.service'].state == 'running'"
  retries: 5
  delay: 5
