---
argument_specs:
  # roles/mysql-backup/tasks/main.yml entry point
  main:
    short_description: Main entry point for the mysql-backup role
    options:
      primary_user:
        type: "str"
        required: false
        default: "replica"
        description: "Mysql replication user."

      primary_password:
        type: "str"
        required: false
        description: "Mysql replication password."

      primary_host:
        type: "str"
        required: true
        description: "Mysql primary server address."

      primary_port:
        type: "int"
        required: false
        default: 3306
        description: "Mysql primary server listening port."
