---
_percona_release_repo:
  Debian: "https://repo.percona.com/apt/percona-release_latest.generic_all.deb"
  RedHat: "https://repo.percona.com/yum/percona-release-latest.noarch.rpm"
percona_release_repo: "{{ _percona_release_repo[ansible_os_family] }}"

mode: "master"
mysql_version: "8.4"
_mysql_major_version: "{{ mysql_version.split('.')[0] }}"
_mysql_minor_version: "{{ mysql_version.split('.')[1] }}"
mysql_version_alias: "{{ _mysql_major_version }}{{ _mysql_minor_version }}"
mysql_port: 3306
mysql_os_user: "mysql"
mysql_os_group: "{{ mysql_os_user }}"
mysql_data_path: "/data0/mysql"
mysql_unix_socket: "{{ mysql_data_path }}/{{ mysql_port }}/mysql.sock"
_mysql_config_file_dict:
  Debian: "/etc/mysql/my.cnf"
  RedHat: "/etc/my.cnf"
mysql_config_file: "{{ _mysql_config_file_dict[ansible_os_family] }}"
_mysql_config_include_dir_dict:
  Debian: "/etc/mysql/mysql.conf.d"
  RedHat: "/etc/my.cnf.d"
mysql_config_include_dir: "{{ _mysql_config_include_dir_dict[ansible_os_family] }}"
_is_initialized_file: "{{ mysql_data_path }}/{{ mysql_port }}/.initialized"

_python_major_version: "{{ ansible_python_version.split('.')[0] }}"
_python_mysql_client_dict:
  Debian: "python{{ _python_major_version }}-pymysql"
  RedHat: "python{{ _python_major_version }}-PyMySQL"
python_mysql_client: "{{ _python_mysql_client_dict[ansible_os_family] }}"

_systemd_mysql_service_dict:
  Debian: "mysql.service"
  RedHat: "mysqld.service"
systemd_mysql_service: "{{ _systemd_mysql_service_dict[ansible_os_family] }}" 

mysql_userlist: []
