---
_percona_release_repo:
  Debian: "https://repo.percona.com/apt/percona-release_latest.generic_all.deb"
  RedHat: "https://repo.percona.com/yum/percona-release-latest.noarch.rpm"
percona_release_repo: "{{ _percona_release_repo[ansible_os_family] }}"

mode: "master"
mysql_version: "8.4"
_mysql_major_version: "{{ mysql_version.split('.')[0] }}"
_mysql_minor_version: "{{ mysql_version.split('.')[1] }}"
mysql_version_alias: "{{ _mysql_major_version }}{{ _mysql_minor_version }}"
mysql_port: 3306
mysql_os_user: "mysql"
mysql_os_group: "{{ mysql_os_user }}"
mysql_instance_root_dir: "/data0/mysql"
mysql_instance_dir: "{{ mysql_instance_root_dir }}/{{ mysql_port }}"
mysql_unix_socket: "{{ mysql_instance_dir }}/mysql.sock"
_is_initialized_file: "{{ mysql_instance_dir }}/.initialized"
mysql_userlist: []

_mysql_config_file:
  Debian: "/etc/mysql/my.cnf"
  RedHat: "/etc/my.cnf"
mysql_config_file: "{{ _mysql_config_file[ansible_os_family] }}"

_mysql_config_include_dir:
  Debian: "/etc/mysql/mysql.conf.d"
  RedHat: "/etc/my.cnf.d"
mysql_config_include_dir: "{{ _mysql_config_include_dir[ansible_os_family] }}"

mysql_multi: false
_mysql_defaults_group_suffix: "{{ '@' ~ mysql_port if mysql_multi else '' }}"
_mysql_instance_name:
  Debian: "mysql{{ _mysql_defaults_group_suffix }}"
  RedHat: "mysqld{{ _mysql_defaults_group_suffix }}"
mysql_instance_name: "{{ _mysql_instance_name[ansible_os_family] }}"

systemd_mysql_service: "{{ mysql_instance_name }}.service"

_python_major_version: "{{ ansible_python_version.split('.')[0] }}"
_python_mysql_client:
  Debian: "python{{ _python_major_version }}-pymysql"
  RedHat: "python{{ _python_major_version }}-PyMySQL"
python_mysql_client: "{{ _python_mysql_client[ansible_os_family] }}"

