---
mode: "master"
mysql_version: "8.4"
_mysql_major_version: "{{ mysql_version.split('.')[0] }}"
_mysql_minor_version: "{{ mysql_version.split('.')[1] }}"
_mysql_version: "{{ _mysql_major_version }}{{ _mysql_minor_version }}"
mysql_os_user:
  name: "mysql"
  comment: "Mysql Server"

_python_major_version: "{{ ansible_python_version.split('.')[0] }}"
_python_mysql_client:
  Debian: "python{{ _python_major_version }}-pymysql"
  RedHat: "python{{ _python_major_version }}-PyMySQL"
python_mysql_client: "{{ _python_mysql_client[ansible_os_family] }}"

_percona_release_repo:
  Debian: "https://repo.percona.com/apt/percona-release_latest.generic_all.deb"
  RedHat: "https://repo.percona.com/yum/percona-release-latest.noarch.rpm"
percona_release_repo: "{{ _percona_release_repo[ansible_os_family] }}"

_systemd_mysql_service:
  Debian: "mysql"
  RedHat: "mysqld"
systemd_mysql_service: "{{ _systemd_mysql_service[ansible_os_family] }}" 


mysql_port: 3306
mysql_data_path: "/data0/mysql"
_is_initialized_file: "{{ mysql_data_path }}/{{ mysql_port }}/.initialized"
_mysql_config_file:
  Debian: "/etc/mysql/my.cnf"
  RedHat: "/etc/my.cnf"
mysql_config_file: "{{ _mysql_config_file[ansible_os_family] }}"
_mysql_config_include_dir:
  Debian: "/etc/mysql/mysql.conf.d"
  RedHat: "/etc/my.cnf.d"
mysql_config_include_dir: "{{ _mysql_config_include_dir[ansible_os_family] }}"

mysql_repl_user:
  name: "repl"
  host: "%"
  passwd: "Faw1gt2wtikpuf597Hrw_"
jumpserver_user:
  name: "jumpserver"
  host: "%"
  passwd: "T7Amfi6a7e+ddknV"
zabbix_user:
  name: "zbx_monitor"
  host: "127.0.0.1"
  passwd: "kdlbVhVkr-37fV3Z6"
