---
- name: Add Grafana Repo
  copy: 
    src: "grafana.repo"
    dest: "/etc/yum.repos.d/grafana.repo"

- name: Install Grafana
  yum:
    name: "grafana"
    state: latest
  notify: restart grafana-server

