---
- name: Install mysqld exporter
  hosts: mysqld_exporter
  tasks:
    - name: Define mysql exporter information
      set_fact:
        _mysqld_exporter_host: "127.0.0.1"
        _mysqld_exporter_port: 3306
        _mysqld_exporter_username: "exporter"
        _mysqld_exporter_password: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_numeric=1, special=false, length=15) }}_"
        _mysqld_exporter_socket: "/data0/mysql/3306/mysql.sock"
    
    - name: Add exporter user
      mysql_user:
        name: "{{ _mysqld_exporter_username }}"
        host: "{{ _mysqld_exporter_host }}"
        password: "{{ _mysqld_exporter_password }}"
        priv: "*.*:REPLICATION CLIENT,PROCESS,SELECT"
        resource_limits:
          MAX_USER_CONNECTIONS: 3
        login_unix_socket: "{{ _mysqld_exporter_socket }}"
        login_user: "root"
        state: present
    
    - name: Install mysqld_exporter
      ansible.builtin.include_role:
        name: prometheus.prometheus.mysqld_exporter
      vars:
        mysqld_exporter_host: "{{ _mysqld_exporter_host }}"
        mysqld_exporter_port: "{{ _mysqld_exporter_port }}"
        mysqld_exporter_username: "{{ _mysqld_exporter_username }}"
        mysqld_exporter_password: "{{ _mysqld_exporter_password }}"
