---
# tasks file for 3proxy
- name: Include os tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Add 3proxy user and password
  shell: "sh /usr/local/3proxy/conf/add3proxyuser.sh {{ item.username }} {{ item.password }}" 
  loop: "{{ threeproxy_userlist }}"

- name: Ensure 3proxy service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: 3proxy
    state: restarted
    enabled: true

- name: Make sure 3proxy service is running
  ansible.builtin.service_facts: {}
  register: __service_status
  until: "__service_status.ansible_facts.services['3proxy.service'].state == 'running'"
  retries: 5
  delay: 5
