---
- name: Install ocserv
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - "ocserv"

- name: Allow ocserv port
  ufw:
    rule: allow
    port: "{{ ocserv_port }}"
    proto: tcp

- name: Allow forwarding policy in UFW
  lineinfile:
    path: /etc/default/ufw
    regexp: '^DEFAULT_FORWARD_POLICY='
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

- name: Add MASQUERADE rule to before.rules
  blockinfile:
    path: /etc/ufw/before.rules
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR NAT"
    insertafter: 'COMMIT'
    block: |
      # NAT table rules
      *nat
      :POSTROUTING ACCEPT [0:0]
      -A POSTROUTING -o {{ ansible_default_ipv4.interface }} -j MASQUERADE
      COMMIT

- name: Reload UFW
  ufw:
    state: reloaded
