---
galaxy_info:
  author: "Barry"
  company: Zeroio
  license: license (BSD)
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 6
        - 7
        - 8
  categories:
    - system
dependencies: []
