---
- name: Add gogs os group
  group:
    name: "{{ gogs_os_group }}"
    state: present
    system: yes

- name: Add gogs os user
  user:
    name: "{{ gogs_os_user }}"
    group: "{{ gogs_os_group }}"
    createhome: yes
    shell: /sbin/nologin
    state: present
    system: yes

      #- name: Create installation directory
      #  file:
      #    path: "{{ item }}"
      #    state: directory
      #    owner: "{{ gogs_os_user }}"
      #    group: "{{ gogs_os_group }}"
      #  with_items:
      #    - "{{ gogs_install_path }}"

- name: Installing gogs
  unarchive:
    src: "{{ gogs_download_url }}"
    dest: "{{ gogs_install_path }}"
    remote_src: yes
    owner: "{{ gogs_os_user }}"
    group: "{{ gogs_os_group }}"


- name: Set systemd gogs service
  template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
  with_items:
    - "gogs.service"

- name: Ensure gogs service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: gogs
    state: restarted
    enabled: true

- name: Make sure gogs service is running
  ansible.builtin.service_facts: {}
  register: __service_status
  until: "__service_status.ansible_facts.services['gogs.service'].state == 'running'"
  retries: 5
  delay: 5
