---
- name: Setup haproxy
  block:
  - name: Include OS Tasks
    include_tasks:
      file: "{{ ansible_os_family }}.yaml"
  
  - name: Setup proxy info
    blockinfile:
      marker: "# {mark} ANSIBLE MANAGED BLOCK FOR HAPROXY"
      dest: "/etc/haproxy/haproxy.cfg"
      block: |
        listen jump
            bind 0.0.0.0:{{ port }}
            mode tcp
            maxconn 2000
            balance roundrobin
            server proxy-{{ port }} {{ inventory_hostname }}:{{ port }}

  - name: Create proxy record
    community.general.cloudflare_dns:
      zone: "{{ zone }}"
      record: "{{ subdomain }}"
      type: A
      solo: true
      value: "{{ proxyip }}"
      api_token: "{{ cloudflare_token }}"

  - name: Restart haproxy
    systemd:
      name: haproxy
      state: restarted
  delegate_to: "{{ proxyip }}"
