---
argument_specs:
  # roles/mysql-replica/tasks/main.yml entry point
  main:
    short_description: Main entry point for the mysql-replica role
    options:
      primary_user:
        type: "str"
        required: false
        default: "replica"
        description: "MySQL replication user."

      primary_password:
        type: "str"
        required: false
        description: "MySQL replication password."

      primary_host:
        type: "str"
        required: true
        description: "MySQL primary server address."

      primary_port:
        type: "int"
        required: false
        default: 3306
        description: "MySQL primary server listening port."

      mysql_unix_socket:
        type: "path"
        required: true
        description: "MySQL default unix socket path."

      primary_unix_socket:
        type: "path"
        required: false
        description: "MySQL primary server unix socket path."

      replica_unix_socket:
        type: "path"
        required: false
        description: "MySQL replication server unix socket path."
