---
 - name: Set network
   block:
   - name: Copy NetworkManager configuration file
     copy: 
       src: conf.d/
       dest: /etc/NetworkManager/conf.d
  
   - name: Restart NetworkManager
     systemd:
       name: NetworkManager
       state: restarted
       enabled: yes
  
   - name: Restart network
     systemd:
       name: network
       state: restarted
       enabled: yes
   when: ansible_distribution_major_version == '7' and ansible_hostname is not search('ALIYUN') and ansible_hostname is not search('AWS')

 - name: Replace resolv.conf
   template: 
     src: redhat.resolv.conf.j2 
     dest: /etc/resolv.conf
   when: ansible_hostname is not search('ALIYUN') and ansible_hostname is not search('AWS')


##对于使用dns进行负载均衡的应用,不建议开启此功能
# - name: Install nscd
#   yum:
#     name: nscd
#     state: present
#
# - name: Copy nscd config
#   copy: 
#     src: nscd.conf
#     dest: /etc/nscd.conf
#
# - name: Restart nscd
#   systemd:
#     name: nscd
#     state: restarted
#     enabled: yes
