---
- name: Install Zabbix-agent2
  yum: 
    name: "{{ item }}"
    enablerepo: zabbix
    state: latest
  loop:
    - "zabbix-agent2"
    - "zabbix-agent2-plugin-*"

- name: Allow zabbix-agent connections
  firewalld:
    zone: public
    port: "{{ item }}"
    immediate: yes
    permanent: true
    state: enabled
  when: mode == "passive"
  with_items:
    - "10050/tcp"
