---
- hosts:
    - os
  roles:
    - role: set_hostname    
    - role: set_nameserver
    - role: set_repo
    - role: set_journald
    - role: install_software
    - role: selinux-disable
    - role: disable_service
    - role: set_firewall
    - role: set_sysctl
    - role: set_time
    - role: set_sshd
    - role: set_passwd
    - role: set_trash
    - role: set_history_format
    - role: set_limits
    - role: swap-disable
    - role: update_kernel
