---
 - name: Include OS Tasks
   include_tasks: "{{ ansible_os_family }}.yml"

 - name: Kube tools bash completion
   shell: "{{ item }} completion bash >/etc/bash_completion.d/{{ item }}"
   loop:
     - kubeadm
     - kubectl

 - name: Initialize master node
   block:
   - name: Copy master init configuration file 
     template:
       src: "kubeadm.yaml.j2"
       dest: "/tmp/kubeadm.yaml"

   - name: Init command
     shell: kubeadm init --config=/tmp/kubeadm.yaml

   - name: Create configuration directory
     file:
       path: $HOME/.kube
       state: directory
 
   - name: Copy configuration file
     copy:
       dest: $HOME/.kube/config
       src: /etc/kubernetes/admin.conf
       remote_src: true

   - name: Deploy network plugin
     include_tasks: "net-weave.yml"

   - name: Deploy view plugin dashboard
     shell: "kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml"
   when: inventory_hostname in groups['master']

 - name: Initialize worker node
   block:
   - name: Get cluster join command
     shell: "kubeadm token create --print-join-command"
     delegate_to: "{{ master_hostname }}"
     register: JOIN_COMMAND
     when: master_hostname is defined

   - name: Worker node join cluster
     shell: "{{ JOIN_COMMAND.stdout }}"
   when: inventory_hostname in groups['worker']

