---
 - name: Deploy network plugin weave
   shell: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
   register: result
   until: result is succeeded
   retries: 5
   delay: 10
