---
- name: Set git user store
  git_config:
    name: "credential.helper"
    scope: global
    value: "store"

- name: Create git credentials
  file:
    path: '/root/.git-credentials'
    owner: root
    group: root
    mode: 0600
    state: touch
