---
- name: Include mysql role vars
  include_role:
    name: mysql
    public: true
    tasks_from: "empty"

- name: Set MySQL replication user information
  set_fact:
   _primary_host: "{{ primary_host }}"
   _primary_port: "{{ primary_port }}"
   _primary_user: "{{ primary_user }}"
   _primary_password: "{{ primary_password | default(lookup('community.general.random_string', min_lower=1, min_upper=1, min_special=1,override_special='_', min_numeric=1, length=16)) }}"
   _primary_unix_socket: "{{ primary_unix_socket | default(mysql_unix_socket) }}"
   _replica_unix_socket: "{{ replica_unix_socket | default(mysql_unix_socket) }}"

- name: Include primary host execution tasks
  include_tasks: "primary.yml"

- name: Stop replication
  mysql_replication:
    login_user: "root"
    login_unix_socket: "{{ _replica_unix_socket }}"
    mode: "stopreplica"

- name: Change replication
  mysql_replication:
    login_user: "root"
    login_unix_socket: "{{ _replica_unix_socket }}"
    primary_host: "{{ _primary_host }}"
    primary_port: "{{ _primary_port }}"
    primary_user: "{{ _primary_user }}"
    primary_password: "{{ _primary_password }}"
    primary_connect_retry: "50"
    primary_ssl: "1"
    primary_auto_position: "1"
    mode: "changeprimary"
  no_log: true

- name: Start replication
  mysql_replication:
    login_user: "root"
    login_unix_socket: "{{ _replica_unix_socket }}"
    mode: "startreplica"

