---
 - name: Include OS Tasks
   include_tasks: "{{ ansible_os_family }}.yml"

 - name: Set Replication
   mysql_replication:
     login_user: "root"
     login_unix_socket: "{{ mysql_data_path }}/{{ replica_port }}/mysql.sock"
     primary_host: "{{ master_host }}"
     primary_port: "{{ master_port }}"
     primary_user: "{{ mysql_repl_user.name }}"
     primary_password: "{{ mysql_repl_user.passwd }}"
     primary_connect_retry: "50"
     primary_ssl: "1"
     primary_auto_position: "1"
     mode: "changereplication"
#   no_log: true

 - name: Start Replication
   mysql_replication:
     login_user: "root"
     login_unix_socket: "{{ mysql_data_path }}/{{ replica_port }}/mysql.sock"
     mode: "startreplica"

