---
# 确保后续setup能将facts存入hostvars中.
# Ensure that subsequent setup can store facts in hostvars.
- name: Add host to inventory
  add_host:
    name: "{{ _primary_host }}"
    group: "dynamic_primary"

# 注意: 如果没有delegate_facts: true, facts会直接存入hostvars[inventory_hostname]中, 而不是存入hostvars[_primary_host]
# Note: If there is no delegate_facts: true, facts will directly storing in hostvars[inventory_hostname] instead of storing them in hostvars[_primary_host]
- name: Gather facts from primary host
  setup:
    gather_subset:
      - min
    filter:
      - "ansible_os_family"
  delegate_to: "{{ _primary_host }}"
  delegate_facts: true

- name: Include primary host tasks [ {{ hostvars[_primary_host].ansible_os_family }} ]
  include_tasks: "primary-{{ hostvars[_primary_host].ansible_os_family }}.yml"

- name: Add relication user on the primary host
  mysql_user:
    name: "replica"
    host: "{{ ansible_default_ipv4.address }}"
    priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT"
    plugin: "caching_sha2_password"
    plugin_auth_string: "{{ _primary_password }}"
    login_unix_socket: "{{ _primary_unix_socket }}"
    login_user: "root"
    state: present
  delegate_to: "{{ _primary_host }}"


