---
 - name: Allow the replica IP on the master node
   firewalld:
     zone: trusted
     source: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
     immediate: yes
     permanent: true
     state: enabled
   delegate_to: "{{ master_host }}"
