- name: Install gogs service
  include_role:
    name: gogs

- name: Install nginx service
  include_role:
    name: nginx
    public: true

- name: Copy gogs nginx configration
  template:
    src: "gogs-nginx.conf.j2"
    dest: "{{ nginx_sites_enabled_dir }}/{{ gogs_domain }}.conf"
  notify: reload nginx

- name: Print gogs webui url
  debug:
    msg: "http://{{ gogs_domain }}"
