---
 - name: Add WWW User Group
   group: 
     name: "{{ user.name }}" 
     gid: "{{ user.id }}" 
     state: present 
     system: yes

 - name: Add WWW User
   user: 
     name: "{{ user.name }}" 
     group: "{{ user.name }}" 
     uid: "{{ user.id }}" 
     createhome: no 
     comment: "{{ user.comment }}" 
     shell: /sbin/nologin 
     state: present 
     system: yes
...
