---
argument_specs:
  # roles/mysql/tasks/main.yml entry point
  main:
    short_description: Main entry point for the mysql role
    options:
      mysql_version:
        type: "str"
        required: false
        default: "8.4"
        description: "Mysql version."

      mode:
        type: "str"
        required: false
        choice:
          - "master"
          - "replica"
        default: "master"
        description: "Mysql "

      mysql_port:
        type: "int"
        required: false
        default: 3306
        description: "Mysql listen port."

      mysql_data_path:
        type: "path"
        required: false
        default: "/data0/mysql"
        description: "Mysql data path."

      mysql_userlist:
        type: list
        elements: dict
        default: []
        description: List of MySQL users to create.
        required: false
        options:
          name:
            type: str
            required: true
            description: Username
          host:
            type: str
            required: true
            description: Host from which the user can connect
          password:
            type: str
            required: true
            description: User's password
          priv:
            type: str
            required: true
            description: User's privilege
