---
argument_specs:
  # roles/mysql/tasks/main.yml entry point
  main:
    short_description: Main entry point for the mysql role
    options:
      mysql_version:
        type: "str"
        required: false
        default: "8.4"
        description: "Mysql version."

      mysql_multi:
        type: "bool"
        required: false
        default: false
        description: "MySQL database multi-instance mode."

      mode:
        type: "str"
        required: false
        choice:
          - "master"
          - "replica"
        default: "master"
        description: "Mysql "

      mysql_port:
        type: "int"
        required: false
        default: 3306
        description: "Mysql listen port."

      mysql_instance_root_dir:
        type: "path"
        required: false
        default: "/data0/mysql"
        description: "Mysql instance directory."

      mysql_instance_dir:
        type: "path"
        required: false
        default: "{{ mysql_instance_root_dir }}/{{ mysql_port }}"
        description: "Mysql instance directory."

      mysql_userlist:
        type: list
        elements: dict
        default: []
        description: List of MySQL users to create.
        required: false
        options:
          name:
            type: str
            required: true
            description: Username
          host:
            type: str
            required: true
            description: Host from which the user can connect
          password:
            type: str
            required: true
            description: User's password
          priv:
            type: str
            required: true
            description: User's privilege

      primary_host:
        type: "str"
        required: true
        description: "MySQL primary server address."

      primary_port:
        type: "int"
        required: false
        default: 3306
        description: "MySQL primary server listening port."

      primary_unix_socket:
        type: "path"
        required: false
        description: "MySQL primary server unix socket path."

      replica_unix_socket:
        type: "path"
        required: false
        description: "MySQL replication server unix socket path."
