---
 - name: Get IP geolocation data
   ipinfoio_facts:

 - name: Install container runtime and debug tool
   apt:
     name: "{{ item }}"
     state: present
   loop:
     - docker.io
     - util-linux    # nsenter

 - name: Make container config directory
   file:
     path: /etc/containerd/
     state: directory

 - name: Touch container config file
   file:
     path: /etc/containerd/config.toml
     state: touch

 - name: Configuration container
   shell: containerd  config default > /etc/containerd/config.toml

 - name: Replace mirror source
   replace:
     path: /etc/containerd/config.toml
     regexp: 'registry.k8s.io'
     replace: 'registry.aliyuncs.com/google_containers'
   when:  country == 'CN'

 - name: Set systemdcgroup
   replace:
     path: /etc/containerd/config.toml
     regexp: 'SystemdCgroup = false'
     replace: 'SystemdCgroup = true'
     
 - name: Restart containerd
   systemd:
     name: containerd
     state: restarted
     enabled: yes

 - name: Copy crictl config
   copy:
     src: crictl.yaml
     dest: /etc/crictl.yaml

 - name: Set crictl bash completion
   shell: "crictl completion bash >/etc/bash_completion.d/crictl"
