__alertmanager_receivers:
  - name: telegram
    telegram_configs:
      - send_resolved: True
        bot_token: "7351480691:AAG36djBjow7yepGJAduNkKYtC2qEMQIJBY"
        chat_id: -4265055206
        parse_mode: "HTML"
        message: '{% raw %}{{ template "telegram.default.message" . }}{% endraw %}'
  - name: telegram-ops
    telegram_configs:
      - send_resolved: True
        bot_token: "7351480691:AAG36djBjow7yepGJAduNkKYtC2qEMQIJBY"
        chat_id: -4265055206
        parse_mode: "HTML"
        message: '{% raw %}{{ template "telegram.default.message" . }}{% endraw %}'

__alertmanager_route:
  group_by:
    - alertname
    - cluster
    - service
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 24h
  receiver: telegram
  routes:
    - receiver: telegram-ops
      matchers:
        - alertname = Watchdog

__alertmanager_inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal:
      - alertname
      - instance

