---
 - name: Set Server Type
   set_fact:
     servertype: "{{ ansible_hostname.split('-')[4] }}"

 - name: SET AIO For Database Backup Server
   sysctl:
     name: "{{ item.name }}"
     value: "{{ item.value }}"
     state: present
     reload: yes
   with_items:
     - {name: fs.aio-max-nr, value: 262144}
   when: ansible_hostname is search('DBB')

 - name: Include Master Tasks
   import_tasks: "mysql_master.yml"

 - name: Include Slave Tasks
   import_tasks: "mysql_slave.yml"
   delegate_to: "{{ mysql_slave_host }}"
   when: ansible_hostname is not search('TS')

...
