---
# handlers file for consul
- name: Restart consul service
  listen: "restart consul"
  become: true
  ansible.builtin.systemd:
    name: consul
    state: restarted
    enabled: true
    daemon_reload: true

- name: Make sure consul service is running
  ansible.builtin.service_facts: {}
  register: __service_status
  until: "__service_status.ansible_facts.services['consul.service'].state == 'running'"
  retries: 5
  delay: 5
