---
 - name: Include OS Tasks
   include_tasks: "{{ ansible_os_family }}.yml"

 - name: Create Trash Directory
   file:
     path: "/trash"
     mode: "u+rwx,g+rwx,o+rwt"
     state: directory

 - name: Cron for clear Trash
   cron:
     name: "Clear Trash"
     minute: "00"
     hour: "5"
     weekday: "3"
     job: "find /trash ! -path /trash -ctime +7 -delete"
     state: present
