- name: Restart php-fpm
  listen: "restart php-fpm"
  become: true
  ansible.builtin.systemd:
    name: "{{ systemd_php_fpm_service }}"
    enabled: true
    daemon_reload: true
    state: restarted
  notify: php-fpm service is running

- name: Reload php-fpm
  listen: "reload php-fpm"
  become: true
  ansible.builtin.systemd:
    name: "{{ systemd_php_fpm_service }}"
    state: reloaded
  notify: php-fpm service is running

- name: Make sure php-fpm service is running
  listen: "php-fpm service is running"
  ansible.builtin.service_facts: {}
  register: __service_status
  until: "__service_status.ansible_facts.services[systemd_php_fpm_service].state == 'running'"
  retries: 10
  delay: 5
