php_version: "8.4"
php_os_user: "www"
php_os_group: "{{ php_os_user }}"
_php_config_file:
  Debian: "/etc/php/{{ php_version }}/fpm/php.ini"
  RedHat: "/etc/php.ini"
php_config_file: "{{ _php_config_file[ansible_os_family] }}"
_php_fpm_confdir:
  Debian: "/etc/php/{{ php_version }}/fpm/pool.d"
  RedHat: "/etc/php-fpm.d"
php_fpm_confdir: "{{ _php_fpm_confdir[ansible_os_family] }}"
php_fpm_logdir: "/var/log/php-fpm"
_systemd_php_fpm_service:
  Debian: "php{{ php_version }}-fpm.service"
  RedHat: "php-fpm.service"
systemd_php_fpm_service: "{{ _systemd_php_fpm_service[ansible_os_family] }}"
