---
 - name: Add Redis User Group
   group:
     name: "redis"
     gid: 301
     state: present
     system: yes

 - name: Add Redis User
   user:
     name: "redis"
     group: "redis"
     uid: 301
     createhome: no
     comment: "Redis Server"
     shell: /sbin/nologin
     state: present
     system: yes

 - name: Install Redis
   yum:
     name: "{{ packages }}"
     state: latest
   vars:
     packages:
       - redis

 - name: Modify /etc/sysctl.conf
   sysctl:
     name: "{{ item.name }}"
     value: "{{ item.value }}"
     state: present
     reload: yes
   with_items:
     - { name: vm.overcommit_memory, value: 1 }

 - name: Create Data Directory
   file:
     path: "{{ item }}"
     group: "{{ redis.group }}"
     owner: "{{ redis.user }}"
     state: directory
   with_items:
         - "{{ redis.data_dir }}/{{ redis.port }}/data"
         - "{{ redis.data_dir }}/{{ redis.port }}/logs"

 - name: Copy Redis Configure 
   template:
     src: "{{ item.filename }}.j2"
     dest: "/etc/redis.conf"
     mode: "{{ item.mode }}"
     group: "{{ redis.group }}"
     owner: "{{ redis.user }}"
   with_items:
     - { 'filename': 'redis-el{{ ansible_distribution_major_version }}.conf', 'mode': '0644' }

 - name: Set Redis Auto Start
   systemd:
     name: redis
     state: restarted
     enabled: yes
     daemon_reload: yes
...
