---
- name: Check MySQL read_only settings
  community.mysql.mysql_variables:
    variable: "read_only"
    login_unix_socket: "{{ mysql_unix_socket }}"
  register: __vars_read_only

- name: Check MySQL super_read_only settings
  community.mysql.mysql_variables:
    variable: "super_read_only"
    login_unix_socket: "{{ mysql_unix_socket }}"
  register: __vars_super_read_only

- name: Add custom MySQL users
  community.mysql.mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    plugin: "caching_sha2_password"
    plugin_auth_string: "{{ item.password }}"
    priv: "{{ item.priv }}"
    #password: "{{ item.password }}"   #MySQL 8.4 deprecates mysql_native_password. Using the password field will cause the mysql_user module to use mysql_native_password when creating users, resulting in an error.
    login_unix_socket: "{{ mysql_unix_socket }}"
    login_user: "root"
    state: present
  loop: "{{ mysql_userlist }}"
  when:
    - __vars_read_only.msg | lower != 'on'
    - __vars_super_read_only.msg | lower != 'on'

