---
- name: Install percona release repo
  yum:
    name: "{{ percona_release_repo }}"
    disable_gpg_check: true
    state: present

- name: Install dependent softwares
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "python{{ _python_major_version }}-libselinux"

- name: Disable selinux
  ansible.posix.selinux:
    state: disabled

