---
# Install mysql
- include_tasks: "installation-{{ ansible_os_family }}.yml"
- include_tasks: "installation.yml"

- name: Add mysql default users
  include_tasks: "users.yml"
  when: mode == "master"      
