- name: Restart nginx
  listen: "restart nginx"
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  notify: nginx service is running

- name: Reload nginx
  listen: "reload nginx"
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  notify: nginx service is running

- name: Make sure nginx service is running
  listen: "nginx service is running"
  ansible.builtin.service_facts: {}
  register: __service_status
  until: "__service_status.ansible_facts.services['nginx.service'].state == 'running'"
  retries: 5
  delay: 5
