---
 - name: Include OS Tasks
   include_tasks: "{{ ansible_os_family }}.yaml"

 - name: Determine The Configuration Directory Of Git
   stat:
     path: "/etc/nginx/.git"
   register: git_stat

 - name: Delete Configuration Directory
   file:
     path: "/etc/nginx"
     state: absent
   when: not git_stat.stat.exists

 - name: Git Clone Configuration
   git:
     repo: "{{ nginx_conf_url }}"
     dest: "/etc/nginx"
     clone: yes
     force: yes

 - name: Create Logs Dir
   file:
     path: "{{ nginx_logs_dir }}" 
     owner: "{{ nginx_user }}"
     group: "{{ nginx_user }}"
     state: directory

 - name: Set Regular Clean Nginx Logs
   template: 
     src: nginx.logrotate.j2
     dest: /etc/logrotate.d/nginx

 - name: Enable Nginx
   systemd:
     name: nginx
     state: restarted
     enabled: yes
     daemon_reload: yes
...
