---
- name: Find instance
  find:
    paths: 
      - "{{ mysql_data_path }}"
    file_type: directory
    patterns: "^[1-5]?[0-9][0-9]?[0-9]?[0-9]?$"
    use_regex: True
  register: instance_list

- name: Set replica_port
  set_fact:
    replica_port: "3307"
  when: instance_list.matched == 0

- name: Set replica_port
  set_fact:
    replica_port: "{{ (instance_list.files | sort(attribute='path') | map(attribute='path') | last | basename | int) + 1 }}"
  when: instance_list.matched != 0

- name: Copy mysqld.cnf
  template:
    src: "mysqld.cnf.j2"
    dest: "{{ mysql_config_include_dir }}/mysqld@{{ replica_port }}.cnf"
    owner: "{{ mysql_os_user.name }}"
    group: "{{ mysql_os_user.name }}"
    mode: "600"

- name: Initail Mysql Instance Directory
  file:
    path: "{{ mysql_data_path }}/{{ replica_port }}/{{ item }}"
    owner: "{{ mysql_os_user.name }}"
    group: "{{ mysql_os_user.name }}"
    recurse: yes
    state: directory
  with_items:
    - data
    - logs/binlog
    - logs/relaylog
    - logs/errorlog
    - logs/slowlog

- name: Determine whether the instance has been initialized
  stat:
    path: "{{ mysql_data_path }}/{{ replica_port }}/.initialized"
  register: file_check

- name: Initialize instance
  command: "/usr/sbin/mysqld --initialize-insecure --user={{ mysql_os_user.name }} --defaults-file={{ mysql_config_include_dir }}/mysqld@{{ replica_port }}.cnf"
  when: not file_check.stat.exists

- name: Create initialized markup file
  file:
    path: "{{ mysql_data_path }}/{{ replica_port }}/.initialized"
    owner: "{{ mysql_os_user.name }}"
    group: "{{ mysql_os_user.name }}"
    state: touch

- name: Start mysql
  systemd:
    name: "mysqld@{{ replica_port }}"
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Include mysql replica role
  include_role: 
    name: mysql-replica

- name: Create mysql slave info file
  file:
    path: "~/mysqlslave.txt"
    state: touch

- name: Record mysql slave info
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR Mysql Slave On Port {{ replica_port }}"
    block: "{{ master_host }}      {{ replica_port }}"
    path: "~/mysqlslave.txt" 
