---
argument_specs:
  # roles/grafana/tasks/main.yml entry point
  main:
    short_description: Main entry point for the grafana role
    options:
      grafana_db_type:
        type: "str"
        required: false
        default: "sqlite3"
        choice:
          - "sqlite3"
          - "mysql"
            #  - "postgres"
        description: "Database type used by Grafana."

