---
argument_specs:
  # roles/zabbix-agent/tasks/main.yml entry point
  main:
    short_description: Main entry point for the zabbix-agent role
    options:
      mode:
        type: "str"
        required: false
        choice:
          - "active"
          - "passive"
        default: "active"
        description: "Zabbix agent mode."

      zabbix_server_hostname:
        type: "str"
        required: false
        description: "Zabbix server hostname."

      set_config:
        type: "bool"
        default: true
        required: false
        description: "Whether to set the configuration file of zabbix-agent"

      proxy:
        type: "bool"
        default: false
        required: false
        description: "Whether to proxy zabbix data"

      zabbix_proxy_hostname:
        type: "str"
        required: false
        description: "Zabbix proxy hostname."

