---
- name: Include os tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Set zabbix mysql password
  set_fact:
    zabbix_mysql_password: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_special=1,override_special='_', min_numeric=1, length=16) }}"

- name: Create web configration directory
  file:
    path: "{{ item }}"
    owner: "{{ php_user }}"
    group: "{{  php_group}}"
    recurse: true
    state: directory
  loop:
    - "/etc/zabbix/web"

- name: Set mysql variables
  community.mysql.mysql_variables:
    variable: log_bin_trust_function_creators
    value: 1
    login_unix_socket: "{{ mysql_socket_path }}"

- name: Import zabbix db
  mysql_db:
    name: "zabbix"
    login_unix_socket: "{{ mysql_socket_path }}"  
    state: import
    encoding: utf8mb4
    collation: utf8mb4_bin
    target: "/usr/share/zabbix-sql-scripts/mysql/server.sql.gz"
    force: true

- name: Set mysql variables
  community.mysql.mysql_variables:
    variable: log_bin_trust_function_creators
    value: 0
    login_unix_socket: "{{ mysql_socket_path }}"

- name: Create zabbix user
  mysql_user:
    name: "zabbix"
    host: "127.0.0.1"
    password: "{{ zabbix_mysql_password }}"
    priv: "zabbix.*:ALL"
    login_unix_socket: "{{ mysql_socket_path }}"
    login_user: "root"
    state: present

- name: Set db pasword in zabbix_server.conf
  blockinfile:
    path: "/etc/zabbix/zabbix_server.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK DBPASSWORD"
    block: |
      DBHost=127.0.0.1
      DBPassword={{ zabbix_mysql_password }}

- name: Copy nginx configuration file
  template:
    src: "nginx.zabbix.com.conf.j2"
    dest: "{{ nginx_sites_enabled_confdir }}/{{ zabbix_server_hostname }}.conf"

- name: Copy phh configuration file
  template:
    src: "php.zabbix.com.conf.j2"
    dest: "{{ php_fpm_confdir }}/{{ zabbix_server_hostname }}.conf"

- name: Restart services
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - "nginx"
    - "{{ php_fpm_systemd_service }}"
    - "zabbix-server"
