---
- name: Install certbot nginx plugin
  apt:
    name: "python3-certbot-nginx"
    state: latest
  when: 
    - certbot_nginx_plugin

- name: Enable certbot timer
  systemd:
    name: certbot.timer
    state: started
    enabled: true
