---
- name: Install zabbix-proxy
  yum: 
    name: "{{ item }}"
    enablerepo: zabbix
    state: latest
  loop:
    - "zabbix-proxy-sqlite3"

- name: Allow zabbix-proxy connections
  firewalld:
    zone: public
    port: "{{ item }}"
    immediate: yes
    permanent: true
    state: enabled
  with_items:
    - "10051/tcp"
