---
- name: Install firewalld
  yum:
    name: firewalld
    state: present

- name: Enable firewalld
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: Set whiteList
  firewalld:
    zone: trusted
    source: "{{ item }}"
    immediate: yes
    permanent: true
    state: enabled
  loop: "{{ internal_whitelist + external_whitelist }}"
