---
 - name: Import Secret Vars
   include_vars: "{{ item }}"
   with_items:
     - "secret.yml"

 - name: Install Zabbix Repo
   yum: 
     name: "{{ packages }}"
     disable_gpg_check: yes
     state: present
   vars:
     packages:
       - "{{ Zabbix_Repo_Url }}"

 - name: Install Pip3 On Centos 7
   yum:
     name: "{{ packages }}"
     state: present
   when: ansible_distribution_major_version == '7'
   vars:
     packages:
       - python36
       - python36-devel
       - python36-pip

 - name: Install Zabbix-agent2
   yum: 
     name: "zabbix-agent2"
     enablerepo: zabbix
     state: latest

 - name: Configure Zabbix_agent2.conf
   template: 
     src: "zabbix_agent2.conf.j2" 
     dest: "/etc/zabbix/zabbix_agent2.conf"

 - name: Rsync Monitor Scripts
   synchronize:
     src: "zabbix_agent2.d"
     dest: "/etc/zabbix/"
     recursive: yes
     archive: no

 - name: Restart Zabbix-agent2
   service:
     name: zabbix-agent2
     state: restarted
     enabled: yes
...
