---
 - hosts: lnmp
   serial: 1
   roles:
     - rpm-nginx
     - rpm-php-fpm
     - mysql

 - hosts: rpm_nginx
   roles:
     - rpm-nginx

 - hosts: rpm_php
   roles:
     - rpm-php-fpm

 - hosts: mysql
   serial: 1
   roles:
     - mysql
...
