---
- name: Add jenkins GPG key
  ansible.builtin.get_url:
    url: "{{ jenkins_gpg_key }}"
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: "0644"

- name: Set up jenkins repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] {{ jenkins_pkg_addr }} binary"
    state: present
    filename: jenkins
    update_cache: yes

- name: Install jave runtime environment
  apt:
    name: "openjdk-17-jre"
    state: latest
