---
 - name: Modify /etc/sysctl.conf
   sysctl: 
     name: "{{ item.name }}" 
     value: "{{ item.value }}" 
     state: present 
     reload: yes
   loop: 
     - {name: net.core.netdev_max_backlog, value: 65535}
     - {name: net.core.somaxconn, value: 65535}
     - {name: net.ipv4.tcp_max_tw_buckets, value: 10000}
     - {name: net.ipv4.tcp_sack, value: 1}
     - {name: net.ipv4.tcp_window_scaling, value: 1}
     - {name: net.ipv4.tcp_max_syn_backlog, value: 65535}
     - {name: net.ipv4.tcp_synack_retries, value: 1}
     - {name: net.ipv4.tcp_syn_retries, value: 2}
     - {name: net.ipv4.tcp_syncookies, value: 1}
     - {name: net.ipv4.tcp_keepalive_time, value: 1200}
     - {name: net.ipv4.tcp_max_orphans, value: 3276800}
     - {name: net.ipv4.tcp_timestamps, value: 1}
     - {name: net.ipv4.tcp_tw_reuse, value: 1}
     - {name: net.ipv4.ip_local_port_range, value: 10000 65000}
#     - {name: net.ipv4.icmp_echo_ignore_all, value: 1}

 - name: Set Google BBR 
   sysctl: 
     name: "{{ item.name }}" 
     value: "{{ item.value }}" 
     state: present 
     reload: yes
   loop: 
     - { name: 'net.core.default_qdisc', value: 'fq' }
     - { name: 'net.ipv4.tcp_congestion_control', value: 'bbr' }
   when: ansible_kernel.split('-')[0] is version_compare('4.9', '>=')
...
