---
- name: Add GRUB superuser configuration
  ansible.builtin.blockinfile:
    path: /etc/grub.d/40_custom
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR GRUB PASSWORD"
    block: |
      set superusers="root"
      password_pbkdf2 root {{ grub_password }}

- name: Update GRUB configuration
  command: update-grub
