---
 - name: Install Basic Software
   apt: 
     name: "{{ packages }}"
     state: present
     update_cache: true
   vars:
     packages:
       - apt-file
       - bash-completion
       - cron
       - git
       - lrzsz
       - rsync
       - screen
       - tree
       - vim
       - wget
       - psmisc               #pstree
       - python3-pip
       - python3-selinux
       - policycoreutils
       - smartmontools
       - zip

 - name: Install Debug Software
   apt: 
     name: "{{ packages }}"
     state: present
   vars:
     packages:
       - bind9-dnsutils        #dig
       - dstat
       - lsof
       - linux-tools-common    #perf
       - iptraf
       - iftop
       - iotop
       - inetutils-ping
       - nload
       - net-tools
       - nethogs
       - mtr
       - strace
       - sysstat
       - tcpdump
       - telnet
       - traceroute
#       - rkhunter
       

 - name: Install Python Software
   pip:
     name: "{{ packages }}"
     state: latest
     executable: pip3
   vars:
     packages:
       - pip
       - setuptools

 - name: Install Certbot
   pip:
     name: "{{ packages }}"
     state: latest
     executable: pip3
   vars:
     packages:
       - certbot

# - name: Add Certbot path
#   file:
#     src: /usr/local/bin/certbot
#     dest: /usr/bin/certbot
#     state: link
...
