---
 - name: Include OS Tasks
   include_tasks: "{{ ansible_os_family }}.yml"

# - block: 
#     - debug:
#         msg: "Change PYPI Source"
#     - file:
#         path: "~/.pip"
#         state: directory
#     - copy:
#         src: "pip.conf"
#         dest: "~/.pip/pip.conf"
...
