---
 - name: Umount swapfile
   ansible.posix.mount:
     path: swap
     state: absent

 - name: Include os tasks
   include_tasks: "{{ ansible_os_family }}.yml"

 - name: Set swap system parameters
   sysctl:
     name: "{{ item.name }}"
     value: "{{ item.value }}"
     state: present
     reload: yes
   loop:
     - {name: vm.swappiness, value: 0}

