---
 - name: Include OS Tasks
   include_tasks: "{{ ansible_os_family }}.yml"

# - name: Add MASQUERADE rule to POSTROUTING chain in the nat table 
#   iptables:
#     table: nat
#     chain: POSTROUTING
#     protocol: all
#     out_interface: "{{ ansible_default_ipv4.interface }}"
#     jump: MASQUERADE

 - name: Copy passwd to remote
   copy:
     src: "sample.passwd"
     dest: "{{ ocserv.confdir }}/sample.passwd" 

 - name: Set ocserv config file
   template:
     src: "{{ ansible_os_family }}.ocserv.conf.j2"
     dest: "{{ ocserv.confdir }}/ocserv.conf"

 - name: Enable ocserv
   systemd:
     name: ocserv
     state: restarted
     enabled: yes

 - name: Enable ip forwarding
   sysctl:
     name: net.ipv4.ip_forward
     value: '1'
     sysctl_set: yes
     state: present
     reload: yes

 - name: Print ocserv link address
   debug:
     msg: "Link: https://{{ inventory_hostname }}:{{ ocserv.port }}"
