---
- name: Install system software [ {{ ansible_os_family }} ]
  apt: 
    name: "{{ packages }}"
    state: latest
    update_cache: true
  vars:
    packages:
      - apt-file
      - bind9-dnsutils        #dig
      - inetutils-ping
      - linux-tools-common    #perf
      - nethogs
      - python3-pip
      - python3-setuptools
      - vim


