---
- name: Install basic software
  yum: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - automake
      - autoconf
      - bash-completion
      - bzip2
        #- gcc
        #- gcc-c++
        #- glibc
        #- glibc-devel
        #- glib2
        #- glib2-devel
      - git
      - httpd-tools
        #- libffi-devel
      - lrzsz
      - make
      - psmisc
      - rsync
      - smartmontools
        #- subversion
      - screen
      - tree
      - unzip
      - vim-enhanced
      - wget
      - zip
      - tar

- name: Install debug software
  yum: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - bind-utils
      - iptraf
      - iftop
      - iotop
      - lsof
      - net-tools
      - nethogs
      - nload
      - mtr
      - perf
      - strace
      - sysstat
      - tcpdump
      - telnet
      - traceroute
#       - tcping
#       - rkhunter
       
- name: Install software [ RHEL == "7" ]
  yum: 
    name: "{{ packages }}"
    state: present
  when: ansible_distribution_major_version == "7"
  vars:
    packages:
      - deltarpm
      - python2-pip
      - python36
      - python-simplejson
      - python-httplib2
      - python-setuptools

- name: Install software [ RHEL >= "8" ]
  yum: 
    name: "{{ packages }}"
    state: present
  when: ansible_distribution_major_version >= "8"
  vars:
    packages:
      - python3-pip
      - python3-setuptools
