---
- name: Determine whether public_key_list is defined
  assert:
    that:
      - "public_key_list is defined"
    fail_msg: "Please copy roles/set_sshd/vars/default.main.yml to roles/set_sshd/vars/main.yml and set public_key_list"

- name: Check if directory exists
  stat:
    path: /etc/ssh/sshd_config.d
  register: dir_result

- name: Copy sshd configuration file
  copy:
    src: 1-ops.conf
    dest: /etc/ssh/sshd_config.d/1-ops.conf
  when: dir_result.stat.exists == true

- name: Modify /etc/ssh/sshd_config
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR SSHD"
    path: "/etc/ssh/sshd_config"
    block: "{{ lookup('file', '1-ops.conf') }}"
  when: dir_result.stat.exists == false

- name: Add authorized_keys
  authorized_key:
    user: root
    key: "{{ item }}"
  loop: "{{ public_key_list }}"

- name: Set ssh timeout
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR SSH TIMEOUT"
    dest: "/etc/profile"
    block: "export TMOUT=900"

- name: Include os tasks
  include_tasks: "{{ ansible_os_family }}.yml"
