---
# - name: Include OS Tasks
#   include_tasks: "{{ ansible_os_family }}.yml"

 - name: Modify /etc/ssh/sshd_config
   blockinfile:
     marker: "# {mark} ANSIBLE MANAGED BLOCK FOR SSHD"
     path: "/etc/ssh/sshd_config"
     block: |
       UseDNS no
       PasswordAuthentication no

 - name: Add Authorized_keys
   authorized_key:
     user: root
     key: "{{ item }}"
   with_file:
     - public_keys/ops

 - name: Set Ssh Timeout
   blockinfile:
     marker: "# {mark} ANSIBLE MANAGED BLOCK FOR SSH TIMEOUT"
     dest: "/etc/profile"
     block: "export TMOUT=900"
