---
 - name: Modify /etc/ssh/sshd_config
   copy: 
     src: sshd_config_{{ ansible_distribution_major_version }}
     dest: /etc/ssh/sshd_config
   notify:
     - Restart Sshd

 - name: Add Authorized_keys
   authorized_key: 
     user: root 
     key: "{{ item }}" 
   with_file: 
     - public_keys/ops

 - name: Set Ssh Timeout
   blockinfile:
     marker: "# {mark} ANSIBLE MANAGED BLOCK FOR SSH TIMEOUT"
     dest: "/etc/profile"
     block: "export TMOUT=900"
...
