- name: Restart mysql
  listen: "restart mysql"
  become: true
  ansible.builtin.systemd:
    name: "{{ systemd_mysql_service }}"
    enabled: true
    daemon_reload: true
    state: restarted
  notify: mysql service is running

- name: Make sure mysql service is running
  listen: "mysql service is running"
  ansible.builtin.service_facts: {}
  register: __service_status
  until: "__service_status.ansible_facts.services[systemd_mysql_service].state == 'running'"
  retries: 5
  delay: 5

