---
 - name: Upgrade Kernel Version
   include_tasks: "upgrade.yml"
   when: ansible_kernel.split('-')[0] is version_compare('4.9', '<')
# - name: Add Elrepo Rpm Gpg Key
#   rpm_key:
#     key: "{{ elrepo_gpg_key_url }}"
#     state: present
#
# - name: Add Elrepo Repo
#   yum:
#     name: "{{elrepo_url}}"
#     state: present
#
# - name: Update Kernel
#   yum:
#     name: "kernel-ml"
#     enablerepo: "elrepo-kernel"
#     state: present
#
# - name: Set Boot Kernel
#   command: grub2-set-default 0 
#
# - name: Reboot
#   reboot:
    
 - name: Set Sysctl Args
   sysctl:
     name: "{{ item.name }}"
     value: "{{ item.value }}"
     reload: yes
     state: present
   with_items:
     - { name: 'net.core.default_qdisc', value: 'fq' }
     - { name: 'net.ipv4.tcp_congestion_control', value: 'bbr' }
