---
 - name: Add Elrepo Rpm Gpg Key
   rpm_key:
     key: "{{ elrepo_gpg_key_url }}"
     state: present

 - name: Add Elrepo Repo
   yum:
     name: "{{elrepo_url}}"
     state: present

 - name: Update Kernel
   yum:
     name: "kernel-ml"
     enablerepo: "elrepo-kernel"
     state: present

 - name: Set Boot Kernel
   command: grub2-set-default 0

 - name: Reboot
   reboot:
