---
- name: Install chrony
  yum:
    name: chrony
    state: latest
  when: ansible_distribution_major_version >= "7"

- name: Enable chrony to sync datetime
  systemd:
    name: chronyd
    state: restarted
    enabled: yes
  when: ansible_distribution_major_version >= "7"
