---
- name: Set port and uuid
  set_fact:
    port: "{{ 65535 | random(seed=subdomain) }}"
    dr_port: "{{ 65535 | random(seed=(subdomain + '-dr')) }}"
    cdn_port: "{{ 65535 | random(seed=(subdomain + '-cdn')) }}"
    uuid: "{{ 99999999 | random(seed=subdomain) | to_uuid }}"
    protocol: "VMess"
    #protocol: "{{ [ 'VMess', 'VLess' ] | random(seed=subdomain) }}"
    #protocol_combination: [ 'VMess', 'VLess' ]

- name: Set link vars
  set_fact:
    link: '{"v":2,"ps":"{{ subdomain }}.{{ zone }}","add":"{{ subdomain }}.{{ zone }}","port":"{{ port }}","id":"{{ uuid }}","aid":"0","net":"ws","host":"{{ subdomain }}.{{ zone }}","path":"/wsv3","tls":"none"}'
    dr_link: '{"v":2,"ps":"{{ subdomain }}-dr.{{ zone }}","add":"{{ subdomain }}-dr.{{ zone }}","port":"{{ dr_port }}","id":"{{ uuid }}","aid":"0","net":"tcp","type":"none","path":""}'
    cdn_link: '{"v":2,"ps":"{{ subdomain }}-cdn.{{ zone }}","add":"{{ subdomain }}-cdn.{{ zone }}","port":"443","id":"{{ uuid }}","aid":"0","net":"ws","host":"{{ subdomain }}-cdn.{{ zone }}","path":"/wsv3","tls":"tls"}'

- name: Include OS Tasks
  include_tasks: "{{ ansible_os_family }}.yaml"

- name: Install v2ray
  shell: "wget -qO- -o- https://git.io/v2ray.sh|bash"
  ignore_errors: true

- name: Create dr record
  community.general.cloudflare_dns:
    zone: "{{ zone }}"
    record: "{{ subdomain }}-dr"
    type: A
    solo: true
    value: "{{ inventory_hostname }}"
    api_token: "{{ cloudflare_token }}"
   
- name: Copy v2ray configuration file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: "{{ protocol }}-WS.json.j2"
      dest: "/etc/v2ray/conf/{{ protocol }}-WS-{{ subdomain }}.{{ zone }}.json"
    - src: "{{ protocol }}-TCP.json.j2"
      dest: "/etc/v2ray/conf/{{ protocol }}-TCP-{{ dr_port }}.json"
    - src: "{{ protocol }}-WS-cdn.json.j2"
      dest: "/etc/v2ray/conf/{{ protocol }}-WS-{{ subdomain }}-cdn.{{ zone }}.json"

- name: Restart v2ray
  systemd:
    name: v2ray
    state: restarted

- name: Include haproxy role
  include_role:
    name: haproxy
  when: proxyip is defined

- name: Include cdn role
  include_role:
    name: cdn

- name: Output v2ray link
  debug:
    msg: |
      {{ protocol | lower }}://{{ link | to_json | b64encode }}
      {{ protocol | lower }}://{{ dr_link | to_json | b64encode }}
      {{ protocol | lower }}://{{ cdn_link | to_json | b64encode }}



