---
 - name: Include OS Tasks
   include_tasks: "{{ ansible_os_family }}.yml"

 - name: Set Swap System ARGS
   sysctl:
     name: "{{ item.name }}"
     value: "{{ item.value }}"
     state: present
     reload: yes
   loop:
     - {name: vm.swappiness, value: 0}
