- name: Install selinux python packages [RedHat]
  ansible.builtin.package:
    name: "{{ ['libselinux-python', 'policycoreutils-python']
           if ansible_python_version is version('3', '<') else
           ['python3-libselinux', 'python3-policycoreutils'] }}"
    state: present
  retries: 5
  delay: 2
  when: ansible_os_family | lower == "redhat"

- name: Install selinux python packages [clearlinux]
  ansible.builtin.package:
    name: sysadmin-basic
    state: present
  retries: 5
  delay: 2
  when:
    - ansible_distribution | lower == "clearlinux"

- name: Disable selinux
  ansible.posix.selinux:
    state: disabled
  when:
    - ansible_selinux.status == "enabled"
