---
- name: Create record
  community.general.cloudflare_dns:
    zone: "{{ zone }}"
    record: "{{ subdomain }}-cdn"
    type: A
    solo: true
    value: "{{ inventory_hostname }}"
    api_token: "{{ cloudflare_token }}"

- name: Include os tasks
  include_tasks:
    file: "{{ ansible_os_family }}.yaml"

- name: Copy Caddyfile
  copy:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile

- name: Create sites directory
  file:
    path: /etc/caddy/sites
    state: directory

- name: Copy site configration file
  template:
    src: site.conf.j2
    dest: "/etc/caddy/sites/{{ subdomain }}-cdn.{{ zone }}.conf"

- name: Restart caddy
  systemd:
    name: caddy
    state: restarted

- name: Create cdn record
  community.general.cloudflare_dns:
    zone: "{{ zone }}"
    record: "{{ subdomain }}-cdn"
    type: A
    proxied: true
    solo: true
    value: "{{ inventory_hostname }}"
    api_token: "{{ cloudflare_token }}"
