---
 - name: Install Firewalld
   yum:
     name: firewalld
     state: present

 - name: Enable Firewalld
   systemd:
     name: firewalld
     enabled: yes
     state: started
   when: ansible_distribution_major_version  >= "7"

 - name: Set WhiteList
   firewalld:
     zone: trusted
     source: "{{ item }}"
     immediate: yes
     permanent: true
     state: enabled
   when: ansible_distribution_major_version  >= "7"
   loop: "{{ whitelist }}"
