---
mysql_repl_user:
  name: "repl"
  passwd: "Faw1gt2wtikpuf597Hrw_"
mysql_os_user:
  name: "mysql"
master_port: 3306
mysql_data_path: "/data0/mysql"
_mysql_config_include_dir:
  Debian: "/etc/mysql/mysql.conf.d"
  RedHat: "/etc/my.cnf.d"
mysql_config_include_dir: "{{ _mysql_config_include_dir[ansible_os_family] }}"
